export { default as About } from "./About";
export { default as Community } from "./Community";
export { default as Landing } from "./Landing";
export { default as LandingLayout } from "./LandingLayout";
export { default as Mapping } from "./Mapping";
export { default as Prevention } from "./Prevention";
export { default as SpecificLbocation } from "./SpecificLocation";
export { default as SignUp } from "./SignUp";
export { default as Login } from "./Login";
